[2024-05-14T05:06:02.238+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T05:06:02.304+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tugas_workflow_v1.task_5 scheduled__2023-10-30T00:00:00+00:00 [queued]>
[2024-05-14T05:06:02.325+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tugas_workflow_v1.task_5 scheduled__2023-10-30T00:00:00+00:00 [queued]>
[2024-05-14T05:06:02.381+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-14T05:06:02.970+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task_5> on 2023-10-30 00:00:00+00:00
[2024-05-14T05:06:03.031+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=846) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T05:06:03.053+0000] {standard_task_runner.py:63} INFO - Started process 877 to run task
[2024-05-14T05:06:03.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tugas_workflow_v1', 'task_5', 'scheduled__2023-10-30T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/prioritas_1.py', '--cfg-path', '/tmp/tmpcc788y86']
[2024-05-14T05:06:03.076+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask task_5
[2024-05-14T05:06:07.771+0000] {task_command.py:426} INFO - Running <TaskInstance: tugas_workflow_v1.task_5 scheduled__2023-10-30T00:00:00+00:00 [running]> on host 0391a550332e
[2024-05-14T05:06:08.386+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sinta' AIRFLOW_CTX_DAG_ID='tugas_workflow_v1' AIRFLOW_CTX_TASK_ID='task_5' AIRFLOW_CTX_EXECUTION_DATE='2023-10-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-30T00:00:00+00:00'
[2024-05-14T05:06:08.392+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T05:06:08.397+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-14T05:06:08.409+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch our_works/works.txt']
[2024-05-14T05:06:08.464+0000] {subprocess.py:86} INFO - Output:
[2024-05-14T05:06:08.472+0000] {subprocess.py:93} INFO - touch: cannot touch 'our_works/works.txt': No such file or directory
[2024-05-14T05:06:08.473+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-14T05:06:08.475+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T05:06:08.497+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-14T05:06:08.507+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tugas_workflow_v1, task_id=task_5, run_id=scheduled__2023-10-30T00:00:00+00:00, execution_date=20231030T000000, start_date=20240514T050602, end_date=20240514T050608
[2024-05-14T05:06:08.546+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 77 for task task_5 (Bash command failed. The command returned a non-zero exit code 1.; 877)
[2024-05-14T05:06:08.578+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-14T05:06:08.601+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
