[2024-05-14T05:16:25.046+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T05:16:25.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tugas_workflow_v1.task_4 scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2024-05-14T05:16:25.122+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tugas_workflow_v1.task_4 scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2024-05-14T05:16:25.123+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-05-14T05:16:25.162+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task_4> on 2023-11-02 00:00:00+00:00
[2024-05-14T05:16:25.175+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1678) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T05:16:25.178+0000] {standard_task_runner.py:63} INFO - Started process 1698 to run task
[2024-05-14T05:16:25.181+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tugas_workflow_v1', 'task_4', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/prioritas_1.py', '--cfg-path', '/tmp/tmpwieqa846']
[2024-05-14T05:16:25.188+0000] {standard_task_runner.py:91} INFO - Job 251: Subtask task_4
[2024-05-14T05:16:25.361+0000] {task_command.py:426} INFO - Running <TaskInstance: tugas_workflow_v1.task_4 scheduled__2023-11-02T00:00:00+00:00 [running]> on host 0391a550332e
[2024-05-14T05:16:25.637+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sinta' AIRFLOW_CTX_DAG_ID='tugas_workflow_v1' AIRFLOW_CTX_TASK_ID='task_4' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2024-05-14T05:16:25.642+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T05:16:25.646+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-14T05:16:25.655+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch about_us/about.txt']
[2024-05-14T05:16:25.695+0000] {subprocess.py:86} INFO - Output:
[2024-05-14T05:16:25.699+0000] {subprocess.py:93} INFO - touch: cannot touch 'about_us/about.txt': No such file or directory
[2024-05-14T05:16:25.701+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-14T05:16:25.702+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T05:16:25.716+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-14T05:16:25.725+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=tugas_workflow_v1, task_id=task_4, run_id=scheduled__2023-11-02T00:00:00+00:00, execution_date=20231102T000000, start_date=20240514T051625, end_date=20240514T051625
[2024-05-14T05:16:25.772+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 251 for task task_4 (Bash command failed. The command returned a non-zero exit code 1.; 1698)
[2024-05-14T05:16:25.817+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-14T05:16:25.846+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
