[2024-05-14T04:35:44.024+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T04:35:44.054+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_numbers_workflow.generate_random_numbers scheduled__2024-05-13T00:00:00+00:00 [queued]>
[2024-05-14T04:35:44.065+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_numbers_workflow.generate_random_numbers scheduled__2024-05-13T00:00:00+00:00 [queued]>
[2024-05-14T04:35:44.066+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-14T04:35:44.085+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_random_numbers> on 2024-05-13 00:00:00+00:00
[2024-05-14T04:35:44.093+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=188) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T04:35:44.096+0000] {standard_task_runner.py:63} INFO - Started process 190 to run task
[2024-05-14T04:35:44.095+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_numbers_workflow', 'generate_random_numbers', 'scheduled__2024-05-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/prioritas_2.py', '--cfg-path', '/tmp/tmpvk71es87']
[2024-05-14T04:35:44.097+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask generate_random_numbers
[2024-05-14T04:35:44.158+0000] {task_command.py:426} INFO - Running <TaskInstance: random_numbers_workflow.generate_random_numbers scheduled__2024-05-13T00:00:00+00:00 [running]> on host 0391a550332e
[2024-05-14T04:35:44.241+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sinta' AIRFLOW_CTX_DAG_ID='random_numbers_workflow' AIRFLOW_CTX_TASK_ID='generate_random_numbers' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-13T00:00:00+00:00'
[2024-05-14T04:35:44.243+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T04:35:44.257+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-14T04:35:44.258+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T04:35:44.266+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_numbers_workflow, task_id=generate_random_numbers, run_id=scheduled__2024-05-13T00:00:00+00:00, execution_date=20240513T000000, start_date=20240514T043544, end_date=20240514T043544
[2024-05-14T04:35:44.311+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T04:35:44.338+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-14T04:35:44.341+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
