[2024-05-20T08:40:11.190+0000] {processor.py:161} INFO - Started process (PID=1188) to work on /opt/airflow/dags/__pycache__/ETL.py
[2024-05-20T08:40:11.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/ETL.py for tasks to queue
[2024-05-20T08:40:11.193+0000] {logging_mixin.py:188} INFO - [2024-05-20T08:40:11.193+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/ETL.py
[2024-05-20T08:40:11.218+0000] {logging_mixin.py:188} INFO - [2024-05-20T08:40:11.213+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/ETL.py", line 2, in <module>
    from airflow.operators import DummyOperator
ImportError: cannot import name 'DummyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-20T08:40:11.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/ETL.py
[2024-05-20T08:40:11.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/ETL.py took 0.056 seconds
[2024-05-20T08:40:41.526+0000] {processor.py:161} INFO - Started process (PID=1253) to work on /opt/airflow/dags/__pycache__/ETL.py
[2024-05-20T08:40:41.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/ETL.py for tasks to queue
[2024-05-20T08:40:41.535+0000] {logging_mixin.py:188} INFO - [2024-05-20T08:40:41.535+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/ETL.py
[2024-05-20T08:40:41.570+0000] {logging_mixin.py:188} INFO - [2024-05-20T08:40:41.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/ETL.py", line 2, in <module>
    from airflow.operators import DummyOperator
ImportError: cannot import name 'DummyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-20T08:40:41.576+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/ETL.py
[2024-05-20T08:40:41.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/ETL.py took 0.106 seconds
[2024-05-20T08:41:11.775+0000] {processor.py:161} INFO - Started process (PID=1316) to work on /opt/airflow/dags/__pycache__/ETL.py
[2024-05-20T08:41:11.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/ETL.py for tasks to queue
[2024-05-20T08:41:11.785+0000] {logging_mixin.py:188} INFO - [2024-05-20T08:41:11.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/ETL.py
[2024-05-20T08:41:11.811+0000] {logging_mixin.py:188} INFO - [2024-05-20T08:41:11.805+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/ETL.py", line 2, in <module>
    from airflow.operators import DummyOperator
ImportError: cannot import name 'DummyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-20T08:41:11.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/ETL.py
[2024-05-20T08:41:11.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/ETL.py took 0.069 seconds
